name: DiscordIntegration Build
# No se que significa exactamente CI, asi que Ok.

on:
  push:
  workflow_dispatch:

env:
  # Para la version 11.0 el link de referencias tiene que ser este https://www.exiled.host/build_deps/Master.zip 
  # Pero si es para la beta https://exiled.host/build_deps/Dev.zip
  EXILED_REFERENCES_URL: https://www.exiled.host/build_deps/Master.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master

    - uses: actions/checkout@v2.3.4

    - name: Get references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/Dev.zip
        Expand-Archive -Path Dev.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}
        Invoke-WebRequest -Uri "https://github.com/SCPStats/Plugin/releases/download/1.4.1/SCPStats.dll" -OutFile ${{ env.EXILED_REFERENCES_PATH }}/SCPStats.dll

    - name: Build
      env:
        EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
      shell: pwsh
      run: |
        ./build.ps1
        $File = (Get-ChildItem -Path . -Include 'EXILED.*.nupkg' -Recurse).Name
        Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Results
        path: ../bin/Debug
